# Generated by Django 6.0.3 on 2026-06-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0003_remove_customuser_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
