# Generated by Django 6.0.3 on 2026-06-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0004_customuser_status_customuser_status_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status_image',
            field=models.ImageField(blank=True, null=True, upload_to='status_images/'),
        ),
    ]
