# Generated by Django 6.0.3 on 2026-06-07 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0005_customuser_status_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reactions_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reactions_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'user', 'emoji')},
            },
        ),
    ]
